### ISSUE TITLE
cannot decode textual union: expected: '{'; actual: '['

### ISSUE THREAD

**Issue by ramneek-grover** [linkedin/goavro#121]
I am getting error `cannot decode textual union: expected: '{'; actual: '['` while native from textual encoding. 

My .avsc file is 
```{
    "namespace": "xyz",
    "type": "record",
    "name": "_value",
    "fields": [
        {
            "name": "label",
            "type": "string",
        },
        {
            "name": "originTypeId",
            "type": "int",
        },
        {
            "name": "domainOriginId",
            "type": ["null", "long"],
            "default": null,
        },
        {
            "name": "hash",
            "type": "string",
        },
        {
            "name": "statusId",
            "type": "int",
        },
        {
            "name": "isVisible",
            "type": ["null", "int"],
            "default": null,
            "doc": "?"
        },
        {
            "name": "objectClass",
            "type":  ["null", {
                "name": "objectClassEnum",
                "type": "enum",
                "symbols": ["DOMAIN","GROUP","USER","COMPUTER","OU","CONTAINER"]
            }],
            "default": null,
        },
        {
            "name": "adGroupIds",
            "type": [
                {
                    "type": "array",
                    "items": "int"
                }
            ],
            "default": []
        }
    ]
}
```

and my json for parsing is 
```{OriginTypeID:7 Label:Administrator Hash:ddd5f081f*&&*^%a5325440 AdGroupIds:[] StatusID:0}```
 
My code:
```
type Value struct {
		OriginTypeID int    `json:"originTypeId"`
		Label        string `json:"label"`
		Hash         string `json:"hash"`
		AdGroupIds   []int  `json:"adGroupIds"`
		StatusID     int    `json:"statusId"`
	} `json:"active_directory_value"`

var structValue Value

func getSchemaCodec(avscFilePath string) (*goavro.Codec){
	schema, err := ioutil.ReadFile(avscFilePath)
	if err != nil {
		panic(err)
	}
	//Create Schema Once
	codec, err := goavro.NewCodec(string(schema))
	if err != nil {
	fmt.Println("Could not able to get encode for schema : ", err.Error())
	}
	return codec
}

codecValue = getSchemaCodec("avscKeyPath")
value, _ := json.Marshal(&structValue)
nativeValue, _,err := codecValue.NativeFromTextual(value)
```
Can anyone help me to resolve this issue. I am badly stuck with it.
Please comment if you want anymore details with this.

**Comment by karrick** [comment]
Avro encoded in JSON required that union values to be encoded in an extra JSON object with a single key, which is the strong name of the data type of that union value, and whose value is the data value.

**Comment by karrick** [comment]
I’ll add some more examples later

**Comment by ramneek-grover** [comment]
@karrick Thank you for replying back. Can you share or point me to any existing or new examples. I have updated the the issue for more clarity.

**Comment by karrick** [comment]
I’m happy to. I know exactly why you are seeing this issue, and I’d be happy to add examples to clarify it a bit more, after I take care of a few things now.

In the meanwhile, an example of a text encoded Avro Union is on the project’s top README.md file.

```Go
func ExampleUnion() {
    codec, err := goavro.NewCodec(`["null","string","int"]`)
    if err != nil {
        fmt.Println(err)
    }
    buf, err := codec.TextFromNative(nil, goavro.Union("string", "some string"))
    if err != nil {
        fmt.Println(err)
    }
    fmt.Println(string(buf))
    // Output: {"string":"some string"}
}
```

**Comment by karrick** [comment]
Take a look at how the text version of that data structure has the type of the value, namely “string” in an embedded JSON object.

**Comment by karrick** [comment]
From the README.md:

When providing a value for an Avro union, the encoder will accept nil for a null value. If the value is non-nil, it must be a map[string]interface{} with a single key-value pair, where the key is the Avro type name and the value is the datum's value. As a convenience, the Union function wraps any datum value in a map as specified above.

**Comment by karrick** [comment]
The problem you’re having is also covered in https://github.com/linkedin/goavro/issues/120

**Comment by karrick** [comment]
Looking at your code, the problem is the fact that Avro _uses_ JSON to represent data in textual format, but not the same JSON that every programming language ever uses, when it comes to *union* types.

```Go
package main

import (
	"encoding/json"
	"fmt"
)

type Value struct {
	OriginTypeID int    `json:"originTypeId"`
	Label        string `json:"label"`
	Hash         string `json:"hash"`
	AdGroupIds   []int  `json:"adGroupIds"`
	StatusID     int    `json:"statusId"`
}

func main() {
	value, err := json.Marshal(&structValue)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(value))
	// Output: {"originTypeId":0,"label":"","hash":"","adGroupIds":null,"statusId":0}
}
```

A couple of things, the `Value` struct in the example in the issue description does not match the Avro schema entirely. That's not a bad thing, because `goavro` does not use code generation and does not populate your data structures for you when you decode into native Go data types, but rather decodes records to `map[string]interface{}`, as described in the README.md file. Anyway, since `goavro` just gives us a `map[string]interface{}`, we would need to use that map to access our data fields. (And the reverse for when we want to encode data. We create a `map[string]interface{}`, populate it to look like the Avro record schema, and send that map to the codec.)

Having said that, when you give `goavro` a JSON representation of data, it needs to be formatted as Avro JSON. Looking at your schema, that JSON would look like this:

```JSON
{
  "label": "some string",
  "originTypeId": 13,
  "domainOriginId": null,
  "hash": "some string",
  "statusId": 42,
  "isVisible": {"int": 99},
  "objectClass": {"objectClassEnum": "CONTAINER"},
  "adGroupIds": {"array": [2, 4, 6, 8]}
}
```

That is what the Avro specification requires for the schema you provided.

A couple of things to notice. First notice that `domainOriginId` was provided a simple JSON `null` value. This is fine because the above schema says that data field is a union, and one of the legal data types is null.

Second, notice that `isVisible` is encoded as `{"int": 99}`. This is because the `isVisible` data type can be either a `null` or an `int`. In this case, I wanted to demonstrate setting the value to some integer, and to do so, the Avro specification states the value must be wrapped in a JSON object with a single key-value pair, and the key is the string name of the type of the value, namely `int` in this example, and that value's key is the value you would like to encode. In this case, 99.

Third, notice the value for the `objectClass` field. That field may also be `null`, or a an `enum`. So this is a great place to demonstrate using an `enum` data field in a union. Simply name the type, like we did for `int` above, but now the data type name is `objectClassEnum`.

Finally, notice the bizarre wrapping around `adGroupIds`. This is because that data field is also an Avro union, a union which has only one legal data type. However, because it is a union, you must wrap that data value with the name of the data type, like `originTypeId`, `isVisible`, and `objectClass`. In this case, the type name for an array is `array`, so that is what that value is wrapped with.

A note. I do not use Avro at all, nor do I recommend its use. If you want an amazingly performant cross platform binary encoding format, seriously consider MessagePack, and for Go the amazing https://github.com/tinylib/msgp is a super great library to use. I use MessagePack when I'm creating a new program and need binary encoding. The MessagePack protocol is a binary encoded protocol that functions identically to JSON. It is trivial to map between JSON and MessagePack.

According to the specification, Avro JSON is JSON, but there are additional rules to apply, especially when you have union data types.

Here's a full example of the code I created to illustrate the differences between regular JSON for your Go `Value` structure, and what the Avro JSON encoding looks like for the schema you provided.

```Go
package main

import (
	"encoding/json"
	"fmt"

	goavro "gopkg.in/linkedin/goavro.v2"
)

type Value struct {
	OriginTypeID int    `json:"originTypeId"`
	Label        string `json:"label"`
	Hash         string `json:"hash"`
	AdGroupIds   []int  `json:"adGroupIds"`
	StatusID     int    `json:"statusId"`
}

func main() {
	example1()
	example2()
}

func example1() {
	var structValue Value
	value, err := json.Marshal(&structValue)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(value))
	// Output: {"originTypeId":0,"label":"","hash":"","adGroupIds":null,"statusId":0}
}

func example2() {
	const avroSchema = `
{
  "type": "record",
  "name": "example2",
  "fields": [
    {"name": "label", "type": "string"},
    {"name": "originTypeId", "type": "int"},
    {"name": "domainOriginId", "type": ["null", "long"], "default": null},
    {"name": "hash", "type": "string"},
    {"name": "statusId", "type": "int"},
    {"name": "isVisible", "type": ["null", "int"], "default": null},
    {
      "name": "objectClass",
      "type": [
        "null",
        {
          "name": "objectClassEnum",
          "type": "enum",
          "symbols": ["DOMAIN", "GROUP", "USER", "COMPUTER", "OU", "CONTAINER"]
        }
      ],
      "default": null
    },
    {
      "name": "adGroupIds",
      "type": [
        {"type": "array", "items": "int"}
      ],
      "default": []
    }
  ]
}`

	codec, err := goavro.NewCodec(avroSchema)
	if err != nil {
		panic(err)
	}

	const avroJson = `
{
  "label": "some string",
  "originTypeId": 13,
  "domainOriginId": null,
  "hash": "some string",
  "statusId": 42,
  "isVisible": {"int": 99},
  "objectClass": {"objectClassEnum": "CONTAINER"},
  "adGroupIds": {"array": [2, 4, 6, 8]}
}
`

	native, _, err := codec.NativeFromTextual([]byte(avroJson))
	if err != nil {
		panic(err)
	}

	fmt.Println(native)
	// Output: map[adGroupIds:map[array:[2 4 6 8]] label:some string originTypeId:13 domainOriginId:<nil> hash:some string statusId:42 isVisible:map[int:99] objectClass:map[objectClassEnum:CONTAINER]]
}
```

**Comment by karrick** [comment]
I forgot to draw attention to this. Here is the output from JSON encoding the `Value` structure:

```JSON
{"originTypeId":0,"label":"","hash":"","adGroupIds":null,"statusId":0}
```

Here is the result of encoding the data in the example above into Avro JSON:

```JSON
{"adGroupIds":{"array":[2,4,6,8]},"domainOriginId":null,"hash":"some string","isVisible":{"int":99},"label":"some string","objectClass":{"objectClassEnum":"CONTAINER"},"originTypeId":13,"statusId":42}
```

Ignoring the different order of the JSON fields, which is actually perfectly legal in JSON, notice the wrapping around the `adGroupIds` field, the `isVisible` field, and the `objectClass` field. Notice also that the final output is just a simple reordering of the JSON fields for the `avroJson` constant in the program, merely not pretty-printed as the input was.

**Comment by ramneek-grover** [comment]
It worked thanks for such a deep description. I need one more help in encoding or enum how it works. do you have any example ?

**Comment by karrick** [comment]
There are lots of examples in `enum_test.go`, but I understand they might not be easy to understand, because they are test code.

The example code I pasted above does encode the enum for the Avro schema you pasted.

`"objectClass": {"objectClassEnum": "CONTAINER"},`

Is that not working?

Paste a copy of your code, and I will try to help you debug it.

**Comment by ramneek-grover** [comment]
Yeah it worked thank you so much.
