### ISSUE TITLE
Using Codec with io.Reader to decode binary/textual into native

### ISSUE THREAD

**Issue by elakito** [linkedin/goavro#125]
I am looking for a way to read the data using Codec in v2.
In v1, I used goavro.Decoder's Decode(io.Reader) to read incrementally the records. This only worked for the binary data. Since v2 supports json-encoding, I am looking for a way to read textual avro using v2's Decoder.
In v2, I see only goavro.Codec and its NativeFromBinary(buf []byte) to read binary data and NativeFromTextual(buf[] byte) to read textual data but these methods uses []byte as input instead of io.Reader.
What I was looking for was something like:

`func (c *Codec) NativeFromTextualReader(r io.Reader) (interface{}, error) `

which decodes the textual input and increments the reader's position at each invocation.

I would like to ask is there such a method or if not, why there isn't.

**Comment by karrick** [comment]
This example file shows one way to read binary avro data:

https://github.com/linkedin/goavro/blob/master/examples/ab2t/main.go

Does that work with your binary Avro file?

**Comment by elakito** [comment]
@karrick  I should have quoted NativeFromTextual(buf []byte) to illustrate my case. I just picked one that has []byte as input instead of io.Reader.

I fixed my text. The test that you refer to is to read avro binary and generate textual records.  What I am looking for is to read textual records and generate a sequence of native records. Is there a way to read textual avro using OCF reader? If there is one, I don't need io.Reader based Codec. But if not, I would like to have one so that I don't have to load everything in memory at once.

**Comment by karrick** [comment]
@elakito,

OCF is defined to contain binary encoded Avro data, so that is not directly supported using the `OCFReader` structure.

**Comment by karrick** [comment]
Because there is no textual equivalent to binary encoded OCF files, you there is no specification for what those files look like. It is likely that you have a bunch of custom OCF-like files, and want to process those, but since they would by a OCF-like file type, a custom file type, there is little reason to put that logic in any Avro library.

My recommendation is to write some custom that reads those files, using the primitives in this library, and writes out new OCF files, which of course will be in binary format.

Were I to attempt such a task, I'd take a long look at the `avroheader` example program to figure out how OCF headers can be read, and once your program reads the header, rather than consuming the file payload using the `OCFReader` construct, to start consuming the payload with the `NativeFromTextual` functions, and append the output to an `OCFWriter` you have already opened.

Once again, since the files you have are a custom format, this task is likely not as cut and dry as I have described. There may be some nuances you will need to overcome.
