### ISSUE TITLE
Question about decimal native representation in version 2.2.6

### ISSUE THREAD

**Issue by elakito** [linkedin/goavro#133]
In version 2.0.4, a decimal value of type bytes is represented as []byte. In contrast, in version 2.2.6, it is represented as *big.Rat. I am not sure about the benefit of using big.Rat because there are a few strange observation.

1. avro json-encoding specifies that the value is represented as []byte, so the textual representation of both 2.0.4 and 2.2.6 use something like {"mydecimal":" \u00D4"} for representing decimal mydecimal. Yet, retrieving its native value, 2.0.4 returns this []byte while 2.2.6 returns its *big.Rat representation.

2. the null-unioned native representation uses map[string]interface{}{"bytes": value}, which means for 2.2.6, it uses []byte in the null-unioned case as in map[string]interface{}{"bytes": []byte{...}}. So when extracting a decimal value from an avro binary record, it may give *big.Rat or []byte depending on how it is typed.

So, somehow I don't see much benefit in using big.Rat as done in 2.2.6. It could have kept []byte as its native decimal representation and provides a utility method to convert it value to big.Rat or float64, etc

I would appreciate for your comments.
Thank you.

regards, aki

**Comment by elakito** [comment]
I noticed this is not limited to decimal. Any logical types that have switch to use time.Time, time.Duration in version 2.2.x have the same behavior. You see int32, int64 etc or time.Time, time.Duration etc.

**Comment by kdvy** [comment]
Hi,

Thanks for the work you've put in here. I should be clear that I don't maintain this repo, I just implemented LogicalTypes in https://github.com/linkedin/goavro/pull/117.

I agree that big.Rat is not ideal however the decision to go with big.Rat was that it allowed for decimal like representation in absence of a native decimal type in Golang itself. float64 is also not appropriate for Decimal use as it suffers precision issues.

Before that PR was merged, logicalTypes were not strictly supported by the library and as per avro specification would fallback to default behaviour of the type field. 

If you would prefer the pre-PR behaviour, then the removal of logicalType field from the schema would allow that.

The intention behind logical types is to allow ease of use for native to avro type conversion. Otherwise individual users of the library would *always* have to convert the types. Whereas now users can have the choice by using logicalTypes or not.

Hope that helps and more than happy to chat about this more,

Kun

**Comment by elakito** [comment]
@kdvy thank you for the explanation. I have no control over the schema, so I can't modify the schema to change the result.

I understand the convenience of using big.Rat for decimal. However, in that case, was it intentional to not using *big.Rat in the nilable decimal type and the old []byte based representation was kept there or was it forgotten to align/update?  I think it is inconvenient to represent a normal decimal as *big.Rat while representing a nilable decimal using []byte as before as in map[string]interface{"bytes":[]byte}. Because that means that the users still need a custom code to be able to process []byte based decimal values.

Would it be better to align the nilable case so that we don't need to handle []byte based decimal in the native representation? If this change violates some requirement, would it then be better to go back to []byte to align those two decimal cases and provide a utility method in goavro.Codec to convert []byte decimal to a more usable *big.Rat?

There is the same misalignment situation  for the other logical types that have changed their native representation from integer based types to time.* based types (i.e., date, time-millis, time-micros, timestamp-millis, timestamp-micros)

thanks.
regards, aki

**Comment by kdvy** [comment]
In the case where you don't have control over the schema itself, a workaround could be to create a new codec using the codec.CanonicalSchema() function which should strip the original schema of it's logicalTypes and give you a logicalType-less codec to return the original behaviour that you seek.

I'm afraid the situation you're describing (the misalignment) is due to logicalTypes being implemented at all. 

There would be no benefit to having logicalTypes if the goavro library returned the field's base type rather than the native type.

**Comment by kdvy** [comment]
A possible work-around to get the pre-logicalType behaviour would be to use codec.CanonicalSchema() to create a new codec which would be logicalType-less. This would revert behaviour for that codec to before the logicalType changes were made. (I apologise for the clunkiness of this work-around)

With regards to null-union cases, the behaviour should be consistent. If the correct schema is provided for the decoding of the avro binary data then the native type e.g. time.Time , time.Duration, big.Rat should be returned. Eg (this is a new test I just wrote for this example):

`func TestDecimalBytesLogicalTypeUnionEncode(t *testing.T) {
    schema := `{"type": ["null", {"type": "bytes", "logicalType": "decimal", "precision": 4, "scale": 2}]}`
    testBinaryCodecPass(t, schema, map[string]interface{}{"bytes.decimal": big.NewRat(617, 50)}, []byte("\x02\x04\x04\xd2"))
}`

For decimals, the native map[string]interface{} field name should be either bytes.decimal or fixed.decimal depending on the schema being used. If you change the bytes.decimal in the example above to just bytes then an error message would be received: 

`cannot encode binary union: no member schema types support datum: allowed types: [null bytes.decimal];`

**Comment by elakito** [comment]
@kdvy Regaring the null-union cases, maybe I had the wrong schema like this
`    {"name": "mydecimal", "type": ["null", "bytes"], "logicalType": "decimal", "precision": 8, "scale": 2}
`
So, it was working fine with goavro.v1 and goavro.v2 until 2.0.4 because []byte was used for both cases, but it lead to the problem mentioned as the above union data is typed as bytes and returned []byte.

Thanks for your explanation. That clarified the second question that I had. I am closing this issue.
