### ISSUE TITLE
Question about BinaryFromNative and TextualFromNative

### ISSUE THREAD

**Issue by elakito** [linkedin/goavro#140]
I would like to create a binary or textual fragment omitting the field values that have default values defined. When I use BinaryFromNative or TextualFromNative and passing an empty map, the default values are included in the generated binary or textual fragment. 

I thought NativeFromBinary or NativeFromTextual would augment the empty fields with the default values so that your application can process the record with the augmented values, but why do BinaryFromNative and TextualFromNative fill the data with the default values? Shouldn't the default values be omitted from being serialized?

For generating an entire binary using OCFWriter works fine for omitting default values.

**Comment by karrick** [comment]
From the [Avro specification](https://avro.apache.org/docs/current/spec.html#schema_record): 

```
default: A default value for this field, used when reading instances that lack this field (optional). Permitted values depend on the field's schema type, according to the table below. Default values for union fields correspond to the first schema in the union. Default values for bytes and fixed fields are JSON strings, where Unicode code points 0-255 are mapped to unsigned 8-bit byte values 0-255.
```

I read the above to mean that the purpose of default values are to allow reading Avro data that was written without the fields, and not necessarily augmentation of data being serialized. So in general I agree with you in terms of purpose.

However, this is where things get messy. One very important aspect of Avro is that the schema used to serialize the data should always remain with the data, so that a reader would always be able to read the schema and then be able to consume the data.

I think most people still agree so far.

However, this is where things get messy. Schema evolution is frequently cited when folks want to use a new version of the schema to read data that was once written using an older version of that schema. I do not believe the Avro specification properly handles schema evolution. Here's a simple example:

User (version 0):
    name: string
    age:    int

Imagine 1000 records written to an OCF file using the above v0 schema.

Next the schema is upgraded to add some fields, and the engineers were thoughtful enough to provide a default value for the new field.

User (version 1):
    name: string
    age:    int
    nickname: string, default: ""

*It is impossible for an engineer wants to use the new schema to read the old data according to the Avro specification*

That is why I advocate against using Avro if at all possible to move away from it.

How could this be? Do not default values allow a person to read the old data using the new schema?

Let's look at how Avro encodes two records using version 0 of the schema:

[{name: "Alice", age: 30}, {name: "Bob", age: 25}]

\x0AAlice\x3C\x06Bob\x32

That is the entire encoding for those two records.

The first byte is 0x0A, which means the following string has 5 bytes, followed by those 5 bytes, namely, "Alice". Then the age is 30, which is encoded as 0x3C (decimal 60). Immediately following the first record comes the next record. Immediately after Alice's record follows Bob's record. Bob's record starts with 0x06 to state there are 3 bytes for the name string, followed by "Bob" as the name bytes, followed by 0x32, which is hexadecimal for 50, which is the encoding for 25.

*NOTE There was no record header stating the size of the first record, and no record break between records.* Keep this thought handy. We'll come back to it.

So what happens when one attempts to use v1 to read bytes encoded using v0? Let's see. Here's the v1 schema for reference:

User (version 1):
    name: string
    age:    int
    nickname: string, default: ""

First of all, the reader just sees a stream of bytes. No record header that specifies the number of bytes the record contains: 0x0A, A, l, i, c, e, 0x3C, 0x06, B, o, b, 0x32.

Imagine looking at that stream using v1:

The reader sees 0x0A, so it knows to consume 5 bytes for the string for the name for the first record. Then it sees 0x3C, which it decodes to 30. Then it sees 0x06. Question, is this the length for an optional nickname for Alice, or is it the length for the name for Bob?

The Avro specification has no answer to that question, so neither do I.

Here's a more sinister example, offered because I'm left-handed.

Record v0:
    name: string
    nickname: string, default: ""

Record v1:
    name: string
    nickname: string, default: ""
    title: string, default: ""

Okay, now a binary stream of records is just a bunch of strings. Let's do that now.

0x0A, A, l, i, c, e, 0x06, B, o, b, 0x0A, B, r, u, c, e, 0x0A, S, a, l, l, y, 0x06, A, n, n

How many records is that? It could be as many as 5 records, each of a single name and no nicknames. It could be as few as 2 records, one of them with a nickname and a title, and one with only a nickname, or a title.

Now to drive home the nail that Avro schema evolution is broken, even if each record had a header that indicated how many bytes it would consume, we could know where one record began and ended, and how many records there are. But if we were to read a record with two strings in it, is the second string the nickname or the title?

The Avro specification has no answer to that question, so neither do I.

Effectively, Avro could be a great tool for serializing complex data, but it's broken in its current form, and to fix it would require it to break compatibility with itself, effectively rendering any binary data serialized in a previous version of Avro unreadable by new versions, unless it had some sort of version marker on the data so a library could branch.

One great solution would be augmenting the binary encoding with a simple field number identifier. Were Avro 2.x to have this feature, then I could get behind using Avro again.

Here's an example:

0x02, 0x0A, A, l, i, c, e, 0x02, 0x06, B, o, B, 0x04, 0x0A, B, r, u, c, e, 0x02, 0x0C, C, h, a, r, l, i, e, 0x06, 0x04, M, r

In the above example of my fake Avro 2.0, this can be deterministically decoded because 0x02 indicates the following is field number 1 (name), followed by string length 5, followed by Alice. Then the decoder would see 0x02, marking field number 1 again, which means, "next record", followed by string length 3, followed by Bob, followed by 0x04, which means field number 2 (nickname), followed by string length 5, followed by Bruce, followed by field number 1 (next record), followed by string length 6, followed by Charlie, followed by field number 3 (title), followed by string length 2, followed by Mr.

In my hypothetical version of Avro 2, Avro can cope with schema evolution using record defaults and such. Sadly, Avro 1.x cannot and thus we should avoid using it if your use-case requires schema evolution.
