### ISSUE TITLE
Flatten "type" arrays of length 1

### ISSUE THREAD

**Issue by maximann** [linkedin/goavro#142]
In `codec.go` when creating a new codec (`NewCodec`) the schema specification is simply unmarshalled using the go json package. Unfortunately, this results in all json arrays of length 1 to have an additional level of indirection in the resulting schema specification.

For example:

```
        "fields": [
          {
            "name": "message",
            "type": [
              "string"
            ]
          }
```

Will result the representation
```
[]
  "name" -> "message"
  "type" -> []
     -> "string"
```

When it could simply be 
```
[]
  "name" -> "message"
  "type" -> "string"
```

This simplification would avoid the unnecessary use of `unions` when (de/)serializing messages.

A simple proposal:
```go
// Flattens types in the unmarshaled codec that are arrays of length 1 (e.g. "type": ["string"]) to a simple type
// (i.e. "type": "string"). This avoids excessive use of unions for schemas that adopt a convention of declaring all
// types in array form.
func flattenCodecTypes(schema interface{}) {
	smap, ok := schema.(map[string]interface{})
	if !ok {
		return
	}

	for k, v := range smap {
		switch k {
		case "fields":
			fa, ok := v.([]interface{})
			if !ok {
				continue
			}

			for _, f := range fa {
				flattenCodecTypes(f)
			}

		case "type":
			ta, ok := v.([]interface{})
			if ok {
				if len(ta) == 1 {
					smap[k] = ta[0]
				}
			} else {
				tm, ok := v.(map[string]interface{})
				if ok {
					flattenCodecTypes(tm)
				}
			}
		}
	}
}
```

To keep changes backwards compatible we would also have to change the `buildCodecForTypeDescribedBySlice` function to handle both, arrays and single value types.

I'd be happy to send a PR, but before that I would like to see what people think of this conceptually.

**Comment by karrick** [comment]
I'm not sure this is a great idea, because the Avro specification defines the exact text based encoding format, specifying both the use of JSON, and the hierarchy and format of the data structures represented by that output, so any Avro text reader can correctly parse.

Creating exception cases outside of the realm of the Avro specification is not within the scope of this project, but certainly something that a person could do for a particular set of data when they themselves have the need for it.
