### ISSUE TITLE
Issue reading goavro encoded avro file in pyspark 2.4

### ISSUE THREAD

**Issue by HakureReimu** [linkedin/goavro#148]
I don't know if this is the right place for this, please close the issue if you think it's not related.
I tried to encode some binary file into avro file using BinaryFromNative and push them to Spark for further processing. When using avro load in pyspark 2.4, it returned "not an avro data file"
`df = spark.read.format("avro").load("file:///root/tmd_unzip/dat1")`
`py4j.protocol.Py4JJavaError: An error occurred while calling o42.load.
: java.io.IOException: Not an Avro data file`

It seemed that spark read avro file with avro schema, which is not included using BinaryFromNative in goavro. So is there a solution to this one?

**Comment by karrick** [comment]
It is very much the proper place for such a question.

As you are aware, Avro is a specification for encoding a datum, and related, OCF is a specification for encoding lots of data values into a binary file that includes the schema and relevant information required for decoding.

If you want to just encode a blob of data, then use the methods `BinaryFromNative` and `TextualFromNative`. But it looks like here that you're trying to write an Avro file, which is really a file that adhere's to the OCF part of the Avro specification.

https://avro.apache.org/docs/current/spec.html#Object+Container+Files

In this case, take a look at the several example programs in the examples directory. Here's one in particular that I like, because while it is a useful utility in itself, allowing someone the ability to rewrite an Avro (OCF) file with different characteristics, it also demonstrates how to read and write OCF files.

https://github.com/linkedin/goavro/tree/master/examples/arw
