### ISSUE TITLE
Can I use this library to read an avro file that has the header?

### ISSUE THREAD

**Issue by invasionofsmallcubes** [linkedin/goavro#171]
This is what I'm trying to do:

```
	file, err := os.Open("./headers/DownLoadHeader.avsc")
	if err != nil {
		panic(err)
	}
	bytes, err := ioutil.ReadAll(file)
	if err != nil {
		panic(err)
	}

	codec, err := goavro.NewCodec(string(bytes))
	if err != nil {
		fmt.Println(err)
	}

	content, err := os.Open("./avro/DownLoadHeader.avro")
	if err != nil {
		panic(err)
	}

	bytesContent, err := ioutil.ReadAll(content)
	if err != nil {
		panic(err)
	}
	
	native, i, err := codec.NativeFromBinary(bytesContent)
	if err != nil {
		panic(err)
	}
	fmt.Println(native)
	fmt.Println(i)
```

but it doesn't work, it breaks.
This file work correctly on apache spark, so I'm pretty sure I'm doing something wrong.

**Comment by karrick** [comment]
You got most of it right. The only thing that is wrong is the last method call. Take a look at the `examples/avro/ab2t/main.go`, specifically the `dumpFromReader`, where it shoved the file pointer into an `OCFWriter` then scans that over and over again, each time emitting a single item from the OCF file.

**Comment by invasionofsmallcubes** [comment]
Hi @karrick , thank you for the help. It's working absolutely fine :)

I have another question if you could answer me:
`datum` inside `textualFromNative` is an interface (well it's a map with the values).

The way `goavro` works with this is to wrap it to text using "textFromNative" and then encodit it using json in a struct?

**Comment by karrick** [comment]
Kind of? When a schema is given to `goavro.NewCodec` it creates and stores 4 trees of function pointers. One function pointer is how to convert a Go native data structure into binary Avro. Another function pointer is how to convert binary Avro back to a Go native data structure. Another function pointer is how to convert Go native data structure into text Avro, which does look like JSON. Finally one function pointer is how to convert the JSON looking text back to Go native data structures. With those 4 function pointers, data can be converted to and from the three formats seamlessly: Go native data structures, binary Avro, and text Avro.

To tackle your specific question, the `Codec.TextualFromNative` method does not convert the Go native data structure into JSON, but converts it into the text based representation that the Avro specification dictates, which happens to be JSON, but very specific. The biggest gotcha that I and other people run into is thinking it's just JSON, but once you get into type unions in your schema, that assumption hits you in the face and it really hurts for a few minutes.

**Comment by karrick** [comment]
I'm closing this issue because you said your program is now working but feel free to post additional comments relating to this issue and I'll get to it when I can.

**Comment by invasionofsmallcubes** [comment]
Just to tell you my approach, it's working, but I created something like this:

```
type SensorLinkedin struct {
	EvaporatorTemperature     *Float `json:"EvaporatorTemperature"`
	CO2reading *Float `json:"CO2reading"`
}

type Float struct {
	Float float64 `json:"double"`
}
```

and then I'm able to parse with a normal 
```
elem, err := textualFromNativeNoGo(codec, datum)
if err != nil {
	fmt.Fprintf(os.Stderr, "%s\n", err)
	continue
}
err = json.Unmarshal(elem, &c)
```

**Comment by karrick** [comment]
There's a bit left undefined in the above, for instance, `textualFromNativeNoGo` is a function that is used there but not described, so I really cannot provide any feedback on what it's doing.

In general if you have an OCF file, usually they have a `.avro` filename extension, then I would humbly recommend using the `OCFReader` to pull the data out one item at a time. Because, as the Avro specification describes, an OCF file is not simply the binary blob of each datum, but rather a file with a header, and zero or more blocks, each with a per-block count of how many data values are in that block in addition to the block size. Additionally, if the header specifies, each block is compressed, and depending on the compression algorithm, each block would have a decompressed checksum to be validated after the block is decompressed. Inside each block, one binary datum is stored right after the previous one. People are of course free to reimplement OCF handling in their own code, or they are free to use the OCF reading capability in `goavro`.

If a particular data file is not OCF, but some other proprietary format that happens to have a bunch of Avro binary blobs in them, then the programmer trying to use this proprietary format would have to implement their own handling, because `goavro` only supports OCF formats for files. Of course, said handling is free to use `goavro`'s decoding capability to decode the binary Avro blobs.

**Comment by invasionofsmallcubes** [comment]
Hi @karrick , thanks for the feedback. I think I'm doing what you are saying, probably it's not explicit from the block of code but here it is:

```
	for ocf.Scan() {
		datum, err := ocf.Read()
		if err != nil {
			logrus.Errorf("Something wrong while parsing %#v\n", err)
			continue
		}
		record, err := textualFromNativeNoGo(codec, datum)
		if err != nil {
			logrus.Errorf("Something wrong while parsing %#v\n", err)
			continue
		}
		records = append(records, p.RecordAggregator.AggregateAvroRecord(&record))
	}
```

and the method `AggregateAvroRecord` is:

```
func (hra *SensorRecordAggregator) AggregateAvroRecord(lineRecords *[]byte) []string {
	
	c := AvroSensors{}
	err := json.Unmarshal(*lineRecords, &c)
	if err != nil {
		logrus.Errorf("Problem formatting json %#v", err)
	}
	return []string{strconv.Itoa(c.DownloadHeaderID.Long),
		c.EventTime.String,
		floatToString(c.SupplyTemperature),
		floatToString(c.ReturnTemperature),
		floatToString(c.TemperatureSetPoint),
		floatToString(c.CO2reading),
		floatToString(c.CO2setpoint),
		floatToString(c.O2reading),
		floatToString(c.O2setpoint),
		boolToString(c.PowerStateOnOff),
		floatToString(c.RelativeHumidity),
		floatToString(c.HumiditySetpoint),
		boolToString(c.HumidityControlOn),
		boolToString(c.O2CO2ControlActive),
	}
}
```
```
