### ISSUE TITLE
Way to generate data example from avro schema?

### ISSUE THREAD

**Issue by JILeXanDR** [linkedin/goavro#212]
As an input I have only any schema in .avro file. In the result I want to get a map this this fields and examples with values according to type and other definitions in schema.

Any worked solutions for this?

Input example:
```
{
  "name": "MyClass",
  "type": "record",
  "namespace": "com.acme.avro",
  "fields": [
    {
      "name": "id",
      "type": "int"
    },
    {
      "name": "type",
      "type": "string"
    },
    {
      "name": "details",
      "type": {
        "name": "details",
        "type": "record",
        "fields": [
          {
            "name": "name",
            "type": "string"
          },
          {
            "name": "data",
            "type": {
              "type": "array"
            }
          }
        ]
      }
    },
    {
      "name": "accounts",
      "type": {
        "type": "array",
        "items": "int"
      }
    }
  ]
}
```
Output example:
```
{
    "id": 0,
    "type": "",
    "details": {
        "name": "",
        "data": []
    },
    "accounts": []
}
```

**Comment by JILeXanDR** [comment]
I wrote my own generator. I close this issue....

**Comment by karrick** [comment]
I just saw this issue today. To answer your question, I do not know of any random data generator that takes an Avro schema and creates data values to populate that schema. I think it is a very interesting idea, but for tests I find just thinking of a few silly data values off the top of my head usually suffices for creating mock data.

If you write one, and feel like sharing a link to it for others to use, feel free to link it in this issue. I certainly would like to see the logic used to populate fields based on what value types they are.

I think the structure of such a program would very much be similar to the structure of the Avro encoders or decoder functions. When invoked each function would be responsible for returning some random values based on the data type. More interesting would be the logic to create such data value generators, because maybe a record field would return data that would fit its intended purpose. For instance, a record field named "name" would return random strings from a list of names. Similarly a record field named "age" might return a random integer.

This certainly is an interesting task, and I hope you are having fun writing it. Good luck!

**Comment by JILeXanDR** [comment]
@karrick Here is a code which I use in my project https://github.com/JILeXanDR/nats-avro-tester/blob/v1.1.4/pkg/avro/schema_example_generator.go

```
var schema map[string]interface{}
json.NewDecoder(avroSchemaFileReader).Decode(&schema)
example, _ := avro.NewExampleGenerator().Generate(schema)
```
`example` is map which stores example as in the question above...
