### ISSUE TITLE
Union type cannot work

### ISSUE THREAD

**Issue by MashiroC** [linkedin/goavro#216]
```go
codec, err := goavro.NewCodec(`
{
	"namespace": "begonia.entry",
	"type": "record",
	"name": "Test",
	"fields": [{
			"name": "id",
			"type": "string"
		},
		{
			"name": "err",
			"type": ["null","string"]                      // <-hear!!!!!
		},
		{
			"name": "result",
			"type": "bytes"
		}
	]
}`)
	if err != nil {
		panic(err)
	}

	d := map[string]interface{}{"id": "test", "err": "test", "result": []byte{1, 2, 3}}
	res, err := codec.TextualFromNative(nil, d)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(res))
```

I got a err:

```
cannot encode textual map: value for "err" does not match its schema: can
not encode textual union: non-nil values ought to be specified with Go map[strin
g]interface{}, with single key equal to type name, and value equal to datum valu
e: [null string]; received: string
```

if I change "err" type to "string", its work.
or if i change map to 
```
d := map[string]interface{}{"id": "test", "err": nil, "result": []byte{1, 2, 3}}
```
its work too

**Comment by karrick** [comment]
This is a frequently asked question, so I [put an example on the main project README to show how to handle unions properly](https://github.com/linkedin/goavro#translating-from-go-to-avro-data).

The Avro spec says that a union must specify which data type the value has. It is the only way the decoder would even know how to read bytes off the line, so to speak, and know how to branch and decode accordingly. When a union may have a null value, the Avro spec allows an optimization where rather than specifying the type as null, a simple null value may be used. Both the JSON and binary Avro formats require this, and therefore the data structures that `goavro` requires mirrors those requirements.

Therefore, the Go native data structures to be provided for a union value needs to be either null, when the union value be null, or a Go map with a single key. The key is the type name of the value, and the value is the actual value.

For instance, to encode "err" above, one needs to pass a native Go `map[string]interface{}{"string":"some error happened"}`. This is quite cumbersome, so I added a helper function, `goavro.Union` which creates the additional data structure elements needed to handle union data types. You can simply set the union's value to the result of calling this function with your union value.

```Go
func ExampleUnion() {
    codec, err := goavro.NewCodec(`["null","string","int"]`)
    if err != nil {
        fmt.Println(err)
    }
    buf, err := codec.TextualFromNative(nil, goavro.Union("string", "some string"))
    if err != nil {
        fmt.Println(err)
    }
    fmt.Println(string(buf))
    // Output: {"string":"some string"}
}
```

**Comment by karrick** [comment]
Please re-open if this explanation does not help you. But do not be afraid to look at the [union_test.go](https://github.com/linkedin/goavro/blob/master/union_test.go) file to provide many examples of transcoding union data values between native and binary, and between native and textual representation, and back again.
