### ISSUE TITLE
Generating a 64-bit Rabin Fingerprint (as recommended in the Avro * spec) of a byte string

### ISSUE THREAD

**Issue by astrekalova** [linkedin/goavro#35]
Avro specification contains description of generating schema fingerprints. Is this functionality supported at all in the goavro package? Can you recommend the best way to generate a schema fingerprint?

**Comment by karrick** [comment]
SHA256 is my personal favorite, because IIRC it's more performant than SHA128.

```Go
fingerprint := fmt.Sprintf("%x", sha256.Sum256(someSchemaString))
```

**Comment by strangesast** [comment]
Do you have an example of using one of these alternative fingerprint methods with a kafka serializer/deserializer? I currently use an avro-cli generated class but it appears the fingerprint method can't be configured ([hard-coded here](https://github.com/apache/avro/blob/2bbb99602e9e925058ead86fc8ac4e27055b05d6/lang/java/avro/src/main/java/org/apache/avro/message/BinaryMessageEncoder.java#L115)).

I would just use the default "CRC-64-AVRO" method, and it's described pretty well in [the avro spec](https://avro.apache.org/docs/1.8.2/spec.html#schema_fingerprints) but I've had trouble implementing it in go.

**Comment by karrick** [comment]
The fingerprint function you referenced one of many hash functions that can be used to convert a long JSON string to a fixed size byte array that hopefully uniquely identifies the schema.

The difficulty is not so much which hash function is used, but the process of converting a non-canonical form of the JSON schema to a canonical form of the JSON schema.

This work has not been done yet for this particular library.

**Comment by karrick** [comment]
I'm taking a look at adding a feature to output the canonicalized JSON version of the schema. The goal is the output of this upcoming function or method will be able to be used as the input for any desired hashing algorithm to get a schema ID.

**Comment by karrick** [comment]
I have merged in some work from a contributor to convert a valid Avro schema to Parsing Canonical Form, and I implemented the CRC-64-AVRO hash suggested in the Avro Specification. Sadly I was unable to find any sample fingerprints using the custom hash function to add to the test suite, so that code has not been merged into the mainline branch yet.

While looking for the sample fingerprints I did find the [Avro Resolution Canonical Form project](https://github.com/salsify/avro-resolution_canonical_form) which aims to complement Parsing Canonical Form by adding a few necessary rules required to fully disambiguate schemas based also on their `default` and `alias` properties.

I suppose the proper course of action is to consider adding the ability to export a schema's Avro Resolution Canonical Form.

**Comment by strangesast** [comment]
Is the solution as simple as rewriting the following (java class) in go?  https://github.com/apache/avro/blob/2bbb99602e9e925058ead86fc8ac4e27055b05d6/lang/java/avro/src/main/java/org/apache/avro/SchemaNormalization.java#L35-L45

I made use of that in [this project](https://github.com/strangesast/avro-parsing-form) to manually generate the parsing form for the avro schemas I need.

I could write a go implementation myself by copying from the java source but it'd be ugly.
