### ISSUE TITLE
avro.codec missing from header

### ISSUE THREAD

**Issue by zak10** [linkedin/goavro#44]
in ocf_reader line 163: 	fr.CompressionCodec, err = getHeaderString("avro.codec", meta)

I'm using hive to compile data into avro format, but it doesn't submit an avro.codec header because we aren't compressing the files. Is there any way to "not require" the header? When I fork and have that line return "null", nil using the library works fine. Could this be an old version of the avro standard?

Thoughts?

**Comment by karrick** [comment]
Great question!

I just took a peek at the Avro 1.8.0 specification, and while goavro was originally targetted at 1.7.7 (iirc), moving forward it should target the most recent specification, especially because specification upgrades shouldn't break things in a backward incompatible manner.

Having said that...

https://avro.apache.org/docs/1.8.0/spec.html#Object+Container+Files

Apparently the *avro.codec* field is not required according to the 1.8.0 specification, and if omitted, the library ought to assume *null* compression. I think it's wise for me to make this change.
