### ISSUE TITLE
Read from Reader does not move forward after an error

### ISSUE THREAD

**Issue by seborama** [linkedin/goavro#65]
If a schema does not specify and default value and the record also fails to provide the value, the Read() method returns an error: `cannot decode long: EOF`.

Problem: f.Scan() detects more records exist but f.Read() resumes from the point of the error rather than skip the erroneous field. As a result the second record is unreadable.

Example:

``` go
package main

import (
    "bytes"
    "fmt"
    "io"
    "log"

    "github.com/linkedin/goavro"
)

func main() {
    w := new(bytes.Buffer)
    makeSomeData(w)
    fmt.Println("Data written")

    dumpReader(w)
}

func makeSomeData(w io.Writer) error {
    recordSchema := `
    {
      "type": "record",
      "name": "example",
      "namespace": "test",
      "fields": [
        {
          "type": "string",
          "name": "username"
        },
        {
          "type": "string",
          "name": "comment"
        },
        {
          "type": "long",
          "name": "timestamp"
        }
      ]
    }
    `
    fw, err := goavro.NewWriter(
        goavro.BlockSize(13),                         // example; default is 10
        goavro.Compression(goavro.CompressionSnappy), // default is CompressionNull
        goavro.WriterSchema(recordSchema),
        goavro.ToWriter(w))
    if err != nil {
        log.Fatal("cannot create Writer: ", err)
    }
    defer fw.Close()

    // make a record instance using the same schema
    someRecord, err := goavro.NewRecord(goavro.RecordSchema(recordSchema))
    if err != nil {
        log.Fatal(err)
    }
    // identify field name to set datum for
    someRecord.Set("username", "Aquaman")
    someRecord.Set("comment", "The Atlantic is oddly cold this morning!")
    // you can fully qualify the field name
    // someRecord.Set("test.timestamp", int64(1082196484))
    fw.Write(someRecord)

    // make another record
    someRecord, err = goavro.NewRecord(goavro.RecordSchema(recordSchema))
    if err != nil {
        log.Fatal(err)
    }
    someRecord.Set("username", "Batman")
    someRecord.Set("comment", "Who are all of these crazies?")
    someRecord.Set("test.timestamp", int64(1427383430))
    fw.Write(someRecord)

    return nil
}

func dumpReader(r io.Reader) {
    fr, err := goavro.NewReader(goavro.BufferFromReader(r))
    if err != nil {
        log.Fatal("cannot create Reader: ", err)
    }
    defer func() {
        if err := fr.Close(); err != nil {
            log.Fatal(err)
        }
    }()

    for fr.Scan() {
        datum, err := fr.Read()
        if err != nil {
            log.Println("cannot read datum: ", err)
            continue
        }
        fmt.Println(datum)
    }
}
```

Execution:

``` bash
$ go run encodeRecord.go
Data written
2016/10/03 23:59:08 cannot read datum:  cannot decode record (test.example): cannot decode long: EOF
2016/10/03 23:59:08 cannot read datum:  cannot decode record (test.example): cannot decode string: cannot decode long: EOF
```

The second error is incorrect: the long has been set on the second record.

The concern here is that one single invalid record prevents from reading all subsequent ones.

**Comment by karrick** [comment]
@seborama,

Thank you for bringing this issue up. The [OCF format in the Avro specification ](https://avro.apache.org/docs/1.8.1/spec.html#Object+Container+Files) specifies that each block consists of one or more Avro objects. It specifies that each block will consist of a block count, a block size, followed by the encoded form of each Avro object. There is no knowledge of how many bytes are in each object, unless the block count is 1, which it isn't guaranteed to be.

Let's say we have an OCF file, and the first block has 10 objects, and is 500 bytes long. Let's say further the decoder is able to decode the first object in the block, consuming 5 bytes. Now there are 495 bytes left for the 9 remaining blocks. The decoder then attempts to decode the second object, but fails after reading 13 bytes.

How many more bytes should it skip to get to the next object? Nobody knows. The point is the data should have decoded correctly, and if it doesn't there is no way to know whether it consumed too many bytes or too few bytes.

The best the OCF reader can do is skip forward to the next block (skipping 500 - 5 - 13 = 482 bytes), and read the next block count, block size, and try decoding the following items.

Even in the best case, the OCF reader has skipped 9 objects which will never be decodable at all, unless the bad bytes are corrected somewhere in the second object it tried to decode.

There is no perfect solution to this problem. The best it can do is perhaps just skip those objects, returning an error that says how many objects were skipped, and move on.

One might be tempted when writing a new OCF file to limit block count to 1. This would allow recovery of the next object whenever an object cannot be decoded. However, blocks are compressed as a unit, and the more objects that are in a block the better compression ratios might be achieved. So there are pros and cons with each attempt.

I still feel that if any object cannot be decoded then the fidelity of the entire OCF is debatable. Avro and OCF on top of Avro intend to be a durable format, but they don't recover well at all from bit flipping due to media error. After starting this library I have found a lot of research papers on this topic, and I'm not convinced the Avro binary format lends itself to durability in the face of this type of error.

**Comment by seborama** [comment]
Thanks for your reply. Very interesting.
All the best.
