### ISSUE TITLE
Use goavro with schema-registry error  Unknown magic byte!

### ISSUE THREAD

**Issue by nut-abctech** [linkedin/goavro#85]
Hi, I'm curious that this lib supports kafka-connect + schema-registry ? 
I've tried to `encode` and sent to kafka topics but the kafka-connect receives message with error Unknown magic byte!. Please give me more info about how to use with them

**Comment by nut-abctech** [comment]
I think, I found out that I need to manually add `magic byte` and `schema id` by myself. So that works for me

**Comment by karrick** [comment]
@nut-abctech,

This library itself doesn't work with Kafka, although it is used along side Kafka every day. At LinkedIn, we get receive a 17-byte header for our Avro messages from Kafka. The first byte is a version byte, the next 16-bytes is the packed MD5 hash of the registered schema used to encode the message. What we do is grab that 16-byte header, lookup the schema ID, download it if not cached, and compile it into a goavro codec. That is then stored in the memoized cache using the schema ID as the key. Finally we decode the payload using the compiled codec.

This functionality is all packaged up as a private library I call gokart, for Go Kafka Avro Resource Tool. I haven't released it openly because I assume the above logic is LinkedIn specific. If this pattern is used outside LinkedIn, I'd be happy to open source that functionality as well.

**Comment by anx-mr** [comment]
@nut-abctech would you please describe how you add the magic byte and schema id manually?
