### ISSUE TITLE
json marshal example

### ISSUE THREAD

**Issue by keith6014** [linkedin/goavro#86]
How do I read a avro file and then Marshal it into json without having extra meta data?

```
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"log"
	"os"

	"github.com/linkedin/goavro"
)

func main() {
	//var i interface{}
	fmt.Println("ok")

	fh, err := os.Open("/home/user/avro/zip.avro")
	if err != nil {
		log.Fatal(err)
	}

	fr, err := goavro.NewReader(goavro.BufferFromReader(io.Reader(fh)))
	if err != nil {
		log.Fatal(err)
	}

	enc := json.NewEncoder(os.Stdout)
	for fr.Scan() {
		d, e := fr.Read()
		if e != nil {
			log.Println(e)
		}
		enc.Encode(d)
	}

}


```

The data looks like this
```
[{"Name":"com.test.avro.MyClass","Fields":[{"Name":"com.test.avro.ZIP","Datum":"00601"},{"Name":"com.test.avro.LAT","Datum":18.180555}
```

How can I get 
```
[{"ZIP":"00601","LAT":18.180555,"LNG":-66.749961},{"ZIP":"00602","LAT":18.361945,"LNG":-67.175597},{"ZIP":"00603","LAT":18.455183,"LNG":-67.119887},{"ZIP":"00606","LAT":18.158345,"LNG":-66.932911}
```
Which is the orignal JSON file. This works in Java

**Comment by karrick** [comment]
Hey, thanks for reaching out for help!

I have completely re-written this library from scratch, and it performs 3 to 4 times faster, and has full JSON support.

https://github.com/karrick/goavro

In fact, the README.md file for the new library shows getting a JSON blob, converting it to native Go data structures, then to Avro binary, then back to native Go data structures, and back to Avro JSON. Because the new library fully supports your use-case, I'm going to go ahead and close this issue. Feel free to open an issue over there if you are unsure how to use it.

I plan on migrating the code from the new version over to this library, but I haven't been able to prioritize it yet. I want to make sure I do it properly, because there is a slight API change, and I don't want people to get terribly inconvenienced.

**Comment by keith6014** [comment]
What is the difference between the linkedin/goavro and karrick/goavro?

**Comment by karrick** [comment]
It's a completely new engine I wrote based on the lessons learned from this engine. I wrote it after I understood namespaces better, so namespaces work correctly rather than almost good enough like in this engine. There were many bugs in this version that proved quite difficult to fix due to its architecture, but I wrote the new engine with an eye towards fixing those bugs.
