### ISSUE TITLE
Why are tests in their own package?

### ISSUE THREAD

**Issue by kklipsch** [linkedin/goavro#87]
By being in their own package they import the goavro package explicitly by pointing at the linkedin path.  When working in a fork this is very problematic.

I've not seen that pattern in other go projects so I'm struggling to see what the benefits are for the downsides?

**Comment by karrick** [comment]
I saw this about 3 years ago. There are pros and cons with this approach, and I've got mixed feelings with it.

On the plus side, when working on the code one is encouraged to test the behavior of the library functions and methods from the user's perspective.

Or more specifically, to write tests that are stable based on the API rather than implementation details.

On the negative side, when working with a fork, one typically has to either temporarily rewrite test files, or use an approach I learned only a few months ago on a different project.

```
cd ~/go/src/github.com/linkedin 
rm -rf goavro
git clone https://path/to/your/forked/goavro
cd goavro
go test
```

If your fork is not uploaded anywhere, you can just move your fork directory rather than git clone.

Give that a shot for now and see whether that helps.

If you still have problems, let me know!

**Comment by kklipsch** [comment]
I can work around it. Was just curious about why it was done.  We can close this issue.

**Comment by karrick** [comment]
I kind of think maybe the proper answer is to not force potential contributors to have to work around something when the benefits are not as clear cut. I'll move things around. Thanks for your feedback.
