### ISSUE TITLE
Simplify nullable JSON field encoding and decoding

### ISSUE THREAD

**Issue by mrauter** [linkedin/goavro#98]
I often use nullable fields in Avro. For that I have to use unions like:
"field" : ["null","string"]

The JSON input and output looks like this:
{ "field": { "string": "value" } }

I would prefer to also support for this format (encode and decode):
{ "field": "value" }

This can be done for all [null, TYPE] unions. For others (e.g. [null, "string", "bytes"]) there should be no change.

You can find a discussion about this here: https://issues.apache.org/jira/browse/AVRO-1582 
I currently use this patch for my Java application, but I want to migrate to golang.

**Comment by karrick** [comment]
I spent a lot of time on this particular issue this past year. Without reading the entire thread, it seems that you'd prefer when the data type is inferrable then to be able to omit the type name declaration from the serialized JSON.

For instance, if the field is `{"name":"field1","type":["null","string","long"]}`, and if 42 was passed to the JSON encoder, then why not simply serialize it as `{"field1":42}`, rather than the more verbose `{"field1":{"long":42}}`?

Is this what you're asking?

If so, then there are a few reasons for not doing this.

While it is more verbose, it uniquely identifies which data type has been serialized. What if the type were `{"name":"field1","type":["null","int","long"]}`, and 42 was again passed to the encoder? Should it specify the data type chosen, because on the decode side, it will likely decode the number as a int64 then need to determine whether it ought to be cast to int32 or not.

It would require every person writing a package to decode Avro JSON data to provide special handling for the data when it is in an embedded map and when it is not, rather than just having one code flow that handles how the data is already encoded.

It's a non-trivial performance hit. Benchmarks revealed that the v1 binary decoding, which used reflection to determine which data type to use required about 4x the time for the operation. While performance might not be important for some people, it is the number 2 goal of this library, right after adhering to the Avro specification.

**Comment by mrauter** [comment]
> Is this what you're asking?

No, as I have wrote I only mean fields with type null + ONE other type

But I agree that as long as it is not in the AVRO standard it should not be implemented. I now use a fork with this "feature" in my application.
